// Copyright 2025 Erst Users
// SPDX-License-Identifier: Apache-2.0

package testgen

// goTestTemplate is the template for generating Go regression tests
const goTestTemplate = `package regression_tests

import (
    "testing"

    "github.com/dotandev/hintents/internal/simulator"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
)

/**
 * FORMAL SCHEMA VALIDATED TEST
 * Generated by: TestGenerator
 * Source Tx: {{.TxHash}}
 */

// TestRegression_{{.TestName}} is a regression test for transaction {{.TxHash}}
func TestRegression_{{.TestName}}(t *testing.T) {
    // Create simulation request with captured transaction data
    req := &simulator.SimulationRequest{
        EnvelopeXdr:   "{{.EnvelopeXdr}}",
        ResultMetaXdr: "{{.ResultMetaXdr}}",
        LedgerEntries: map[string]string{
{{- range .LedgerEntries}}
            "{{.Key}}": "{{.Value}}",
{{- end}}
        },
    }

    // Create simulator runner
    runner, err := simulator.NewRunner("", false)
    require.NoError(t, err, "Failed to create simulator runner")

    // Run simulation
    resp, err := runner.Run(req)
    require.NoError(t, err, "Simulation failed")

    // Assert expected behavior
    assert.Equal(t, "success", resp.Status, "Expected successful simulation")
    assert.NotEmpty(t, resp.Logs, "Expected simulation logs")
    
    t.Logf("Simulation completed successfully")
    t.Logf("Events: %v", resp.Events)
    t.Logf("Logs: %v", resp.Logs)
}
`

// rustTestTemplate is the template for generating Rust regression tests
const rustTestTemplate = `use serde_json;
use std::collections::HashMap;

/**
 * FORMAL SCHEMA VALIDATED TEST
 * Generated by: TestGenerator
 * Source Tx: {{.TxHash}}
 */

// Test data structures (should match main.rs)
#[derive(serde::Serialize)]
struct SimulationRequest {
    envelope_xdr: String,
    result_meta_xdr: String,
    ledger_entries: Option<HashMap<String, String>>,
}

#[derive(serde::Deserialize, Debug)]
struct SimulationResponse {
    status: String,
    error: Option<String>,
    events: Vec<String>,
    logs: Vec<String>,
}

/// Regression test for transaction {{.TxHash}}
#[test]
fn test_regression_{{.TestName}}() {
    // Create simulation request with captured transaction data
    let mut ledger_entries = HashMap::new();
{{- range .LedgerEntries}}
    ledger_entries.insert("{{.Key}}".to_string(), "{{.Value}}".to_string());
{{- end}}

    let request = SimulationRequest {
        envelope_xdr: "{{.EnvelopeXdr}}".to_string(),
        result_meta_xdr: "{{.ResultMetaXdr}}".to_string(),
        ledger_entries: if ledger_entries.is_empty() {
            None
        } else {
            Some(ledger_entries)
        },
    };

    // Serialize request to JSON
    let request_json = serde_json::to_string(&request).expect("Failed to serialize request");

    // Placeholder for simulator binary execution
    println!("Regression test for {{.TxHash}} - Formal Schema Validated");
}
`
